default: cpsc2150/sets/ArraySet.java cpsc2150/sets/DoubleSetApp.java cpsc2150/sets/ISet.java cpsc2150/sets/ListSet.java cpsc2150/sets/SetAbs.java
	javac cpsc2150/sets/ArraySet.java cpsc2150/sets/DoubleSetApp.java cpsc2150/sets/ISet.java cpsc2150/sets/ListSet.java cpsc2150/sets/SetAbs.java

run: cpsc2150/sets/ArraySet.class cpsc2150/sets/DoubleSetApp.class cpsc2150/sets/ISet.class cpsc2150/sets/ListSet.class cpsc2150/sets/SetAbs.class
	java cpsc2150.sets.DoubleSetApp

clean:
	rm -f cpsc2150/sets/*.class
